### PR TITLE
Pipeline and per project configuration support

### PR DESCRIPTION
**Pull request by butchyyyy**
PR contains several improvements to the plugin:
* Support for DSL/Pipeline jobs
* Per project configuration
* Posting to fixed topic
* New build step that allows sending arbitrary messages
* Automated tests

### CODE REVIEW

**Review by eeshangarg — CHANGES_REQUESTED** [review]
@butchyyyy: Thanks a lot for working on this! Sorry for the late review, I've been awfully busy with school and everything, and I am barely keeping up with my work backlog! Anyway, I have a couple of comments:

* First of all, I would recommend separating this PR into multiple commits. This PR constitutes a massive change to this plugin and would be much easier to review/merge if I could view every particular change separately. For example, I'd have a separate commit for configuring a topic to send messages to and a separate commit for configuring a stream and topic per project, and so on.

* Also, I'd recommend structuring the commit messages like so: `jenkins: Support configuring topic per project.` You can learn more about our commit guidelines [here](https://zulip.readthedocs.io/en/latest/contributing/version-control.html).

* I would also recommend reading our [writing guidelines for documenting integrations](https://zulip.readthedocs.io/en/latest/subsystems/integration-docs.html#writing-guidelines) and seeing if we can make sure we conform to that in the `README` as much as possible. Also, it might be worth it to submit a PR on the zulip/zulip repo updating the [Jenkins integration docs](https://zulipchat.com/integrations/doc/jenkins) as well!

If you have any questions, feel free to message me on `chat.zulip.org`! Thanks again!

\-Eeshan

**Comment by eeshangarg** [comment]
@butchyyyy: This looks much better! I took a close look at all of the commits and everything LGTM! I do think the documentation (README) may need some improvements here and there but let's do that in another PR after this one gets merged! :) Thanks for working on this!

**Comment by butchyyyy** [comment]
@eeshangarg: Thanks a lot for taking the time to look at this. Looking back at the README i noticed some typos and i'm sure there are other improvements to be made since i'm not an native english speaker. I'll be happy to improve it once this is merged.

**Comment by timabbott** [comment]
Merged!  @butchyyyy huge thanks for your work on this.  I really appreciate your taking the time to do a high-quality cleanup of this plugin!

**Comment by timabbott** [comment]
It is probably worth doing a round of triage together on the remaining open issues and PRs for this project, just to check which of them you've already fixed.

**Pull request merged**
